server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JavaSpring-TrIT/ejercico_voluntario-Davbp
          default-label: main
          search-paths:
          - /config

